apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      project: backend-pod
  template:
    metadata:
      labels:
        project: backend-pod
    spec:
      containers:
        - name: backend-pod
          image: paraslov/backend-for-devops:latest
          env:
            - name: PORT
              value: "8000"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
  