apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend-pod
spec:
  containers:
    - name: frontend-pod
      image: frontend:latest
      ports:
        - containerPort: 3000